feat: reset token and mailer
xgeekshq/divide-and-conquer pull request #117
Opened 2022-04-01 14:01 UTC by r-dmatos

Relates to  #108

## Screenshots (if visual changes)

## Proposed Changes
  -  Mailer module was used to handle the reset password emails.
  - A 1 minute timer was implemented to the reset password flow to prevent extra requests ( there might be a better way to do this ) 
  - Env files updated with mailer module options

2022-04-13 10:46 UTC, nunocaseiro commented
@all-contributors please add @r-dmatos for code and doc

2022-04-13 11:23 UTC, rpvsilva requested changes

2022-04-13 11:23 UTC, rpvsilva commented on backend/src/infrastructure/database/mongoose.module.ts
> +export const mongooseResetModule = MongooseModule.forFeature([
```suggestion
]);

export const mongooseResetModule = MongooseModule.forFeature([
```

2022-04-13 11:23 UTC, rpvsilva commented on backend/src/modules/auth/controller/auth.controller.ts
> +  }
```suggestion
  forgot(@Body() { email }: EmailParam) {
    return this.createResetTokenAuthApp.create(email);
  }
```

2022-04-13 11:23 UTC, rpvsilva commented on backend/src/modules/auth/services/create-reset-token.auth.service.ts
> +  private frontendUrl = this.configService.get<string>('frontend.url');
set this variable before the constructor and then set it inside it

2022-04-13 11:23 UTC, rpvsilva commented on backend/src/modules/auth/services/create-reset-token.auth.service.ts
> +    return { message: 'please check your email' };
Define a constant with this message

2022-04-13 11:23 UTC, rpvsilva commented on backend/src/modules/auth/services/create-reset-token.auth.service.ts
> +        return await this.emailBody(token, emailAddress);
You should commit the transaction after the `emailBody`, so set a constant and await for the method and then commit then return

2022-05-06 09:54 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-05-06 10:30 UTC, rpvsilva submitted a review, later dismissed
LGTM 🚀

2022-05-20 12:50 UTC, nunocaseiro approved these changes

2022-05-20 12:51 UTC, merged