feat: dashboard statistics and get all boards with pagination
xgeekshq/divide-and-conquer pull request #125
Opened 2022-04-08 11:57 UTC by nunocaseiro

Relates to #123

## Proposed Changes

  - Method in auth controller to retrieve some statistics about the authenticated user
  - Get all boards service method depending of the user's role and atual page in the frontend. 
     - If dashboard -> all boards of user of the last 3 months
     - if boards page and the user is super admin -> all boards 
     - if boards page and the user is not super admin -> all boards of user

This pull request is intended to close #123

2022-04-08 13:32 UTC, rpvsilva requested changes

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/infrastructure/config/jwt.register.ts
> +  useFactory: async (configService: ConfigService) => ({
```suggestion
  useFactory: (configService: ConfigService) => ({
```

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/modules/auth/controller/auth.controller.ts
> +    const boardsCount = await this.getBoardApp.countBoards(userId);
```suggestion
    const [usersCount, teamsCount, boardsCount] = await Promise.all([
      this.getUserApp.countUsers(),
      this.getTeamsApp.countTeams(userId),
      this.getBoardApp.countBoards(userId),
    ]);
```

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/modules/boards/controller/boards.controller.ts
> +      return this.getBoardApp.getBoards('allBoards', userId, page, size);
```suggestion
    if (isSAdmin) {
      return this.getBoardApp.getBoards('allBoards', userId, page, size);
    }
```

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/modules/boards/controller/boards.controller.ts
> +    return this.getBoardApp.getBoards('dashboard', userId, page, size);
You don't need to destructure the user object

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/modules/boards/services/get.board.service.ts
> +    const teamIds = await this.getTeamService.getTeamsOfUser(userId);
```suggestion
    const [boardIds, teamIds] = await Promise.all([
      this.getAllBoardsIdsOfUser(userId),
      this.getTeamService.getTeamsOfUser(userId)
    ])
```

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/modules/boards/services/get.board.service.ts
> +      );
```suggestion
      const now = new Date();
      const last3Months = new Date(now.setMonth(now.getMonth() - 3));
```

2022-04-08 13:32 UTC, rpvsilva commented on backend/src/modules/boards/services/get.board.service.ts
> +    option: 'dashboard' | 'allBoards' | 'myBoards',
I think this logic shouldn't be in server side, you just need to be concerned about the limit and offset sent by the client, the client is the one that needs to be concerned about what he wants to get

2022-04-11 14:43 UTC, rpvsilva commented on backend/src/modules/boards/services/get.board.service.ts
> +    return { boards, hasNextPage, page };
here you are doing 2 requests each time to check if there is a next page, let's merge it and get a better solution for it

2022-04-11 14:43 UTC, rpvsilva approved these changes

2022-04-11 14:52 UTC, nunocaseiro commented on backend/src/modules/boards/services/get.board.service.ts
> +    return { boards, hasNextPage, page };
yes, I think we can do it with the aggregator method from mongo. We need to put more effort on it. Let's merge it then

2022-04-11 14:56 UTC, rpvsilva approved these changes

2022-04-11 14:57 UTC, merged