[Feature] Manual Sign up
xgeekshq/divide-and-conquer pull request #167
Opened 2022-05-13 09:49 UTC by f-morgado

Relates to #109 

## Screenshots (if visual changes)
![image](https://user-images.githubusercontent.com/99803749/168258005-d23da3c6-9f9b-485e-b8c8-4db5d0ae381d.png)
![image](https://user-images.githubusercontent.com/99803749/168258173-e5f5890e-cee3-4934-8361-d84f0b204077.png)
![image](https://user-images.githubusercontent.com/99803749/168258521-f113da04-7a74-40f1-aed5-6eb463bba27f.png)

## Proposed Changes

  - Verification if an email is already registered and if so, send the user back to log in page
  - New logo and banner on the main frame
  - verification on all the fields necessary for the sign up
  - SSO and non SSO mail verification

2022-05-13 10:29 UTC, nunocaseiro reviewed
The backend package-lock.json should be commited as we only use the one that is in the project root folder

2022-05-13 10:49 UTC, nunocaseiro requested changes

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/Primitives/Input.tsx
> +    console.log(icon);
You should clean all the console.log

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +      },
```suggestion
      onSuccess: (data) => {
        console.log(" entrou onsucess", data);
        if (data === "az") {
         setShowSignUp(SignUpEnum.SIGN_UP_OPTIONS);
         return;
        }
        if (data === false) {
          setShowSignUp(SignUpEnum.REGISTER);
          return;
        }
        setValueHelperText(" This email already exists");
        setValueState(true);
      },
```

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +          console.log(" on submit", email);
Clear the console.log

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/Primitives/Checkbox.tsx
> +          //  backgroundColor: "$primaryBase",
remove the comment please

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/Primitives/Checkbox.tsx
> +  // eslint-disable-next-line react/require-default-props
remove this eslint disable rule

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/Primitives/Checkbox.tsx
> +    console.log("click ;)");
console.log eheh

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/RegisterForm.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
remove this eslint disable

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +      },
and remove the eslint

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +        console.log("entrou onerror");
clear console.log

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +    console.log("handleCheckUserExists");
clear

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpOptionsForm.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
remove this line

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpOptionsForm.tsx
> +  // const [ShowLogIn, setShowLogIn] = useState(false);
and this

2022-05-13 10:49 UTC, nunocaseiro commented on frontend/components/auth/SignUp/SignUpOptionsForm.tsx
> +        {/* {`${textContent}`} */}
and this

2022-05-16 13:12 UTC, f-morgado commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +      },
fixed

2022-05-16 13:12 UTC, f-morgado commented on frontend/components/Primitives/Checkbox.tsx
> +          //  backgroundColor: "$primaryBase",
fixed

2022-05-16 13:13 UTC, f-morgado commented on frontend/components/auth/SignUp/SignUpOptionsForm.tsx
> +        {/* {`${textContent}`} */}
done

2022-05-16 13:14 UTC, f-morgado commented on frontend/components/auth/SignUp/SignUpOptionsForm.tsx
> +  // const [ShowLogIn, setShowLogIn] = useState(false);
done

2022-05-16 13:14 UTC, f-morgado commented on frontend/components/auth/SignUp/SignUpForm.tsx
> +        console.log("entrou onerror");
done

2022-05-17 10:40 UTC, nunocaseiro commented
@all-contributors please add @f-morgado  for code and doc

2022-05-17 10:49 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-05-17 10:51 UTC, merged

2022-05-17 10:52 UTC, f-morgado commented
ty for all the time you took helping me Nuno 🦾