Feature create getall board be
xgeekshq/divide-and-conquer pull request #50
Opened 2021-11-16 10:47 UTC by nunocaseiro

Relates to #47

## Proposed Changes

  - Board controller with multiples endpoints such as create board, get boards, get board by id and update locked board
  - Board, column and card entities
  - Board, column and card dtos to also validate the incoming data
 
This pull request is intended to close #47

2021-11-16 17:11 UTC, rpvsilva requested changes

2021-11-16 17:11 UTC, rpvsilva commented on backend/src/boards/entity/board.entity.ts
> +  createdBy: string;
Since you are doing a relation for the user here, you could use the `typeorm` [relations](https://typeorm.io/#/relations) feature

2021-11-16 17:11 UTC, rpvsilva commented on backend/src/boards/entity/card.entity.ts
> +  createdBy: string;
Same as above

2021-11-16 17:11 UTC, rpvsilva commented on backend/src/boards/boards.service.ts
> +    return newBoard;
```suggestion
    return this.boardsRepository.save(newBoard);
```

2021-11-16 17:11 UTC, rpvsilva commented on backend/src/boards/boards.service.ts
> +      throw new HttpException(BOARD_NOT_FOUND, HttpStatus.NOT_FOUND);
Line line !33 you are returning an exceptions and in !44 you are throwing one, just use the throw for exceptions and do it line 
```javascript
if(boards) return boards;

throw ...
```

2021-11-16 17:54 UTC, nunocaseiro commented on backend/src/boards/boards.controller.spec.ts
> +    }).compile();
sure! it was auto generated by nest cli :p

2021-11-16 20:03 UTC, nunocaseiro commented on backend/src/boards/entity/board.entity.ts
> +  createdBy: string;
I think we need to change from typeorm to mongoose because the first is more focused on SQL databases, dont support relations with mongo. The nestjs documentation also suggest using mongoose with mongodb as the most popular MongoDB object modeling tool. 
source: [https://docs.nestjs.com/techniques/mongodb#mongo](url)

2021-11-17 00:05 UTC, nunocaseiro commented on backend/src/boards/entity/board.entity.ts
> +  createdBy: string;
Typeorm relations don't work with mongodb as this is a nosql db but I can change the string type to user type. However we don't obtain nothing more from that :)

2021-11-17 13:26 UTC, asantos00 commented on backend/src/boards/boards.service.ts
> +        _id: new ObjectId(boardId),
pardon my random jump into this PR, but this service shouldn't be coupled with MongoDB at all, it's the repository's responsibility to interact with MongoDB and thus know that ObjectId needs to be instantiated

2021-11-17 13:27 UTC, asantos00 commented on backend/src/boards/boards.service.ts
> +    if (board.locked && password && isPasswordMatched) return board;
this board.locked is redundant, if the code gets here, it will already by locked because of the condition on line 47

2021-11-17 13:29 UTC, asantos00 commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
Isn't this automatically created by mongo? This is completely out of curiosity

2021-11-17 13:30 UTC, asantos00 commented on backend/src/boards/entity/content.ts
> +  _id: ObjectId;
Just to clarify, is this _id the same thing in which we used the `uuidv4` function call above?

2021-11-17 13:32 UTC, asantos00 commented on backend/src/constants/jwt.ts
> +export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
Not that it's super relevant, but ES6 Symbols can be used here. They generate unique keys and make it pretty much impossible to use the string version, because it doesn't exist: https://riptutorial.com/javascript/example/15827/implementing-enums-using-symbols

Just a matter of curiosity

2021-11-17 14:24 UTC, nunocaseiro commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
Yes, it is automatically created by mongo when the main document is created. I just post a body with board data with columns and cards as an array so they are nested objects. As I need the Id in the frontend of this nested documents, it's necessary to generate it manually. The ids are not mandatory but I am using the ids of nested objects as key prop on map method of render in frontend. [Here](https://github.com/chnirt/chnirt-demo-nest-typeorm-mongodb/blob/master/src/modules/user/user.entity.ts), [here](https://medium.com/@chnirt/how-do-i-practice-with-nestjs-nestjs-typeorm-mongodb-9e407818a296) and [here](https://stackoverflow.com/questions/10144852/how-can-i-create-unique-ids-for-embedded-documents-in-mongodb) they are also using uuid or objectId to generate id before insert :) Maybe I'm doing something wrong

2021-11-17 14:39 UTC, nunocaseiro commented on backend/src/boards/entity/content.ts
> +  _id: ObjectId;
Here I am defining the columns of an entity

2021-11-17 14:48 UTC, asantos00 commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
Wait, so the main reason we're creating these ids is to have a key prop on the front-end? 
This manual generation of ids, together with other problems you are having (namely not being able to establish proper relations on the ORM) should trigger a discussion on if we're using the correct data storage (SQL vs NOSQL).

However, even if we decide to go with generating id's manually (besides all the flags it might raise), it shouldn't be done this way. What if you change your MongoDB configuration and the id's are not uuid v4 anymore? Will you have to change all your code? Doesn't make much sense, right?

Manual generation of ids should be done like the following:

```js
const mongodb = require("mongodb")

const newId = mongodb.ObjectId().toString()
```

2021-11-17 14:51 UTC, asantos00 commented on backend/src/boards/entity/content.ts
> +  _id: ObjectId;
So, why is it a string above and here an objectId?

2021-11-17 15:00 UTC, nunocaseiro commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
Yes, atm the created ids are just for the key prop in frontend. I agree with you, we need to discuss if we should continue with nosql. In the meanwhile I will replace uuid v4 with your suggestion. Thank you for the help

2021-11-17 15:07 UTC, asantos00 commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
It seems strange to me that, to fix a front-end problem, to be more specifically a react problem, we're adding a field on the database. These things shouldn't be this coupled, it also doesn't seem like the right solution. 
There are many ways to generate unique keys on the front-ent that don't depend on the database, don't we agree?

2021-11-17 15:54 UTC, nunocaseiro commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
Yes, I agree with you, my bad. im still with the relational db mindset and I didn't know what the best approach would be. We don't need an extra field in db. So, if i need to generate a unique id in frontend do you have any suggestion? Is uuid v4 a good ideia?

2021-11-17 16:01 UTC, asantos00 commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
You can probably generate the keys on the frontend by adding multiple fields, like title + color + index, even hashing them if needed. This is the better solution. Then, if not possible, you can use multiple packages, which uuid is one of them, to generate keys

2021-11-17 16:04 UTC, nunocaseiro commented on backend/src/boards/dto/column.dto.ts
> +  _id: string = uuidv4();
Thank you! :)

2021-11-17 18:15 UTC, rpvsilva requested changes

2021-11-17 18:15 UTC, rpvsilva commented on backend/src/boards/boards.controller.ts
> +  async boards(@Req() request: RequestWithUser) {
Since you removed the `await` you can remove the `async`. Do it everywhere

2021-11-17 18:15 UTC, rpvsilva commented on backend/src/boards/boards.service.ts
> +    throw new HttpException(BOARD_NOT_FOUND, HttpStatus.UNAUTHORIZED);
Just make the validation to throw the exceptions first and do the logic after it like:

```javascript
if (board.createdBy.email !== email) throw new HttpException(BOARD_NOT_FOUND, HttpStatus.UNAUTHORIZED);
```

2021-11-17 22:52 UTC, rpvsilva commented on backend/src/boards/boards.service.ts
> +
Noticed now that after I requested that changes here you are checking by the password argument after using it to compare... Sorry about that

2021-11-17 22:53 UTC, rpvsilva commented on backend/src/boards/boards.service.ts
> +    return await this.getBoardFromRepo(boardId);
Remove the await 😂 Sorry for being so annoying

2021-11-17 23:40 UTC, nunocaseiro commented on backend/src/boards/boards.service.ts
> +    return await this.getBoardFromRepo(boardId);
its ok bro! thanks for the help. sometimes im blinded ahah

2021-11-18 10:45 UTC, rpvsilva approved these changes

2021-11-18 10:53 UTC, rpvsilva commented
Nice work here 🔥

2021-11-18 11:03 UTC, merged