refactor: airbnb eslint rules used as well as prettier
xgeekshq/divide-and-conquer pull request #53
Opened 2021-11-23 12:01 UTC by nunocaseiro

## Proposed Changes

  - Added esling airbnb rules and adapted the code

2021-11-23 14:55 UTC, rpvsilva commented on .gitignore
> +.env.production
Since you removed all `.env` files, can you add a `.env.example` where you put the keys used as an example to new developers that join this project?

2021-11-25 20:56 UTC, rpvsilva requested changes

2021-11-25 20:56 UTC, rpvsilva commented on backend/src/constants/config.ts
> +export default PORT;
Since this is a config file why are you defaulting the `PORT`?

2021-11-25 20:56 UTC, rpvsilva commented on backend/src/constants/encrypt.ts
> +export default SALT;
Same as above

2021-11-25 21:29 UTC, nunocaseiro commented on backend/src/constants/config.ts
> +export default PORT;
Yeah, I understand what you say. The eslint rule "prefer default export" is warning me. Should i disable it in this file?

2021-11-26 14:22 UTC, rpvsilva commented on backend/src/constants/config.ts
> +// eslint-disable-next-line import/prefer-default-export
Instead of disabling the rule, you could remove that rule, I think the developer could choose if wants to use an `export default` or not. Just my opinion 😂

2021-11-26 14:32 UTC, nunocaseiro commented on backend/src/constants/config.ts
> +// eslint-disable-next-line import/prefer-default-export
Yes, i agree with you. I just disabled it

2021-11-29 14:05 UTC, rpvsilva approved these changes

2021-11-29 14:07 UTC, merged