feature: websocket be
xgeekshq/divide-and-conquer pull request #58
Opened 2021-11-30 11:47 UTC by nunocaseiro

Relates to #57

## Proposed Changes

  - Websocket gateway with socket.io
  - Method to handle the socket connections, mapping the websocket client id to the board room
  - When the user moves some card or column, the frontend will send a message via websocket that is handled by the developed method in backend. This receives a payload of changes, transform the board with them and updates the board in database. Finally propagates the changes to all users that are seeing the same board.

2021-12-03 10:18 UTC, rpvsilva requested changes

2021-12-05 15:49 UTC, nunocaseiro commented on backend/src/boards/boards.controller.ts
> +      passwordDto.password,
I didn't have the tsconfig rule enabled so the answer is no. I enabled it and handled the errors. Thanks for the feedback

2021-12-06 12:08 UTC, rpvsilva commented on backend/src/main.ts
> +  if (PORT) await app.listen(PORT);
Instead of verify if PORT is defined could you just use a default port? this way we know that the backend runs every time, and do a `console.log` telling that the app is running at X port: `API is running at http://localhost:${PORT}`

2021-12-06 14:59 UTC, rpvsilva commented on backend/src/main.ts
> +  logger.log(`Application is running at http://localhost:${PORT}`);
If you don't set a PORT it will log as undefined right? Check for the PORT before and set it to a variable and then use it here

2021-12-06 15:10 UTC, nunocaseiro commented on backend/src/main.ts
> +  logger.log(`Application is running at http://localhost:${PORT}`);
I changed the config file. Btw, the application never starts with `PORT` undefined because before it starts, it also check if the .env file has the required env vars through the joi schema validation that is in `app.module.ts` file :)

2021-12-06 15:26 UTC, rpvsilva approved these changes
LGTM 🔥  Nice job

2021-12-06 15:44 UTC, merged