feat: share, edit title and delete board from the dashboard
xgeekshq/divide-and-conquer pull request #65
Opened 2021-12-20 12:10 UTC by nunocaseiro

Relates to #64

## Screenshots 

![Captura de ecrã 2021-12-20, às 12 00 34](https://user-images.githubusercontent.com/90208434/146764657-11a6c2f5-5745-4a91-9e18-0c8abed5c536.png)
![Captura de ecrã 2021-12-20, às 12 01 56](https://user-images.githubusercontent.com/90208434/146764662-16fd6e64-bd28-4a41-a798-eb3999979083.png)
![Captura de ecrã 2021-12-20, às 12 02 10](https://user-images.githubusercontent.com/90208434/146764669-6c1f980e-c194-4bcc-9691-61a27a02f834.png)

## Proposed Changes

  - Implementation of a feature that allows the user to copy the board url to clipboard from the dashboard
  - Implementation of a feature that allows renaming the board from the dashboard
  - Implementation of a feature that allows the user to delete a board the dasboard

The visual proposed changes are possible to see in the screenshots above.

This pull request is intendend to close #64

2022-01-03 12:55 UTC, jomifepe requested changes
A couple things that could be changed, but great job on this 💪

2022-01-03 12:55 UTC, jomifepe commented on frontend/api/boardService.tsx
> +export const updateTitleBoard = ({
Nitpicking, just to improve readibility

```suggestion
export const updateBoardTitle = ({
```

Don't forget to change in other places

2022-01-03 12:55 UTC, jomifepe commented on frontend/components/Dashboard/BoardList/CardBody.tsx
> +        )}
We should always make sure we have a boolean when using logic operators for conditional rendering. (ref: https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator)

```suggestion
        {!!board.columns && (
          <Flex gap="8">
            <HandleCols columns={board.columns} />
          </Flex>
        )}
```

2022-01-03 12:55 UTC, jomifepe commented on frontend/components/Dashboard/BoardList/CardHeader.tsx
> +        }}
I think it's more readable if we extract a function like `handleCopy` to the component's scope instead of writing it in the JSX, this applies for every `onClick` and similar event properties.

2022-01-03 12:55 UTC, jomifepe commented on frontend/components/Dashboard/CreateBoardModal.tsx
> +      });
Shouldn't some of this logic be moved closer and to the server? Like to `postBoard` method. 

Also, a couple other things:
- `createdBy` should probably be handled on the server by decoding the token
-  The `columnsOrder` should be generated on the server side, depending on our `columns` array order, ids should also never be generated on the client side
- The token should already be set to the axios common headers to be sent in every authenticated request.

2022-01-03 14:31 UTC, jomifepe commented on frontend/components/Dashboard/BoardList/CardBody.tsx
> +    <Link key={board._id} href={`boards/${board._id}`}>
These routes could be extracted to a `routes.ts` constants file, and be used like: `ROUTES.BOARD_PAGE(board._id)`

2022-01-03 14:32 UTC, jomifepe commented on frontend/components/Dashboard/BoardList/CardBody.tsx
> +    <Link key={board._id} href={`boards/${board._id}`}>
These routes could be extracted to a `routes.ts` constants file, and be used like: `ROUTES.BOARD_PAGE(board._id)`

2022-01-03 19:37 UTC, nunocaseiro commented on frontend/components/Dashboard/BoardList/CardBody.tsx
> +        )}
thanks for the tip!!

2022-01-06 17:54 UTC, nunocaseiro commented on frontend/components/Dashboard/CreateBoardModal.tsx
> +      });
As we spoked, this changes will be fixed on the next PR with the new ORM - mongoose - and with the new data schema

2022-01-06 22:48 UTC, jomifepe submitted a review, later dismissed
Some final suggestions and you can merge away 🚀

2022-01-06 22:48 UTC, jomifepe commented on frontend/components/Dashboard/CreateBoardModal.tsx
> +        <form onSubmit={handleSubmit((data: BoardType) => handleClick(data))}>
```suggestion
        <form onSubmit={handleSubmit(handleClick)}>
```

2022-01-06 22:48 UTC, jomifepe commented on frontend/components/Dashboard/CreateBoardModal.tsx
> +          {errors.title && (
```suggestion
          {!!errors.title && (
```

2022-01-06 22:48 UTC, jomifepe commented on frontend/components/Dashboard/BoardList/CardBody.tsx
> +      })}
Can the `column.color` field be undefined? I searched for it and I believe it's a string

```suggestion
      {columns.map((column) => (
          <HoverCardRoot key={column._id}>
            <HoverCardTrigger asChild>
            <Circle
               variant="circle"
               align="center"
               justify="center"
               css={{
                  color: "white",
                  backgroundColor: column.color || "gray",
               }}
            >
              {column.cardsOrder.length}
            </Circle>
            </HoverCardTrigger>
            <HoverCardContent sideOffset={0}>
              {column.title}
              <HoverCardArrow />
            </HoverCardContent>
          </HoverCardRoot>
        ))}
```

2022-01-06 22:48 UTC, jomifepe commented on frontend/components/Layout/Layout.tsx
> +    instance.defaults.headers.common.Authorization = `Bearer ${session?.accessToken}`;
This can't be here, it's being executed on every rerender. 
It needs to be on a `useEffect` at least.

But I don't think it's the right place to set the token, weren't you able to find a place after login?

```suggestion
useEffect(() => {
  if (status === "authenticated" && session?.accessToken) {
    instance.defaults.headers.common.Authorization = `Bearer ${session?.accessToken}`;
  }
}, [status])
```

2022-01-06 23:25 UTC, nunocaseiro commented on frontend/components/Layout/Layout.tsx
> +    instance.defaults.headers.common.Authorization = `Bearer ${session?.accessToken}`;
Thanks bro, I just fixed that

2022-01-07 12:07 UTC, jomifepe approved these changes
LGTM 🔥

2022-01-07 12:18 UTC, merged