feat: create, update, delete comments
xgeekshq/divide-and-conquer pull request #82
Opened 2022-02-14 12:28 UTC by nunocaseiro

Relates to #79

## Proposed Changes

  - Create, update and delete services
  - Comments controller with post, put and delete methods
  - Create, update and delete applications (use-cases)

This pull request is intended to close #79

2022-02-18 15:38 UTC, rpvsilva requested changes

2022-02-18 15:38 UTC, rpvsilva commented on backend/src/modules/cards/services/create.card.service.ts
> +    if (card.items.length === 0) {
You can do this, or you can create an util to verify if a value is empty, you can reach me to help you with it 😉 

```suggestion
    if (!card.items.length) {
```

2022-02-18 15:38 UTC, rpvsilva commented on backend/src/modules/comments/controller/comments.controller.ts
> +  @Post(':id/card/:cardId/items/:itemId/comment')
Can you change the `:id` to `:boardId`

2022-02-18 15:38 UTC, rpvsilva commented on backend/src/modules/comments/controller/comments.controller.ts
> +  @Put(':id/card/:cardId/items/:cardItemId/comment/:commentId')
As above

2022-02-18 15:38 UTC, rpvsilva commented on backend/src/modules/comments/controller/comments.controller.ts
> +  @Delete(':id/card/:cardId/items/:cardItemId/comment/:commentId')
Again

2022-02-18 15:38 UTC, rpvsilva commented on backend/src/modules/comments/services/create.comment.service.ts
> +
```suggestion
        )
```

2022-02-18 15:38 UTC, rpvsilva commented on backend/src/modules/comments/services/delete.comment.service.ts
> +    }
Just a question, since you have this operation inside a `try { ... } catch(ex) { ... }` and if you throw an error on the `try` and you get it on `catch` and then you throw the same error, does this make sense? Or you can just remove the `try { ... } catch(ex) { ... }` and throw it anyway?

2022-02-20 16:19 UTC, rpvsilva requested changes

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/auth/services/register.auth.service.ts
> +    return createdUser;
```suggestion
    return this.createUserService.create({
      ...registrationData,
      password: hashedPassword,
    });
```

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/auth/services/validate-user.auth.service.ts
> +    return user;
If this method returns null by it self, it's not necessary to check and just return its response

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/comments/services/delete.comment.service.ts
>    async deleteItemComment(boardId: string, commentId: string, userId: string) {
```suggestion
  deleteItemComment(boardId: string, commentId: string, userId: string) {
```

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/comments/services/update.comment.service.ts
> +    return this.boardModel.findOneAndUpdate(
Remove the `async` on this method too

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/users/services/update.user.service.ts
>    async setCurrentRefreshToken(refreshToken: string, userId: string) {
```suggestion
  setCurrentRefreshToken(refreshToken: string, userId: string) {
```

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/boards/services/update.board.service.ts
>    async update(userId: string, boardId: string, boardData: BoardDto) {
```suggestion
  update(userId: string, boardId: string, boardData: BoardDto) {
```

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/boards/services/get.board.service.ts
>    async getAllBoards(userId: string) {
```suggestion
  getAllBoards(userId: string) {
```

2022-02-20 16:19 UTC, rpvsilva commented on backend/src/modules/boards/applications/delete.board.application.ts
> +  async delete(boardId: string, userId: string): Promise<boolean> {
```suggestion
  delete(boardId: string, userId: string): Promise<boolean> {
```

2022-02-20 18:26 UTC, nunocaseiro commented on backend/src/modules/users/services/update.user.service.ts
>    async setCurrentRefreshToken(refreshToken: string, userId: string) {
this method has an await on the encrypt promise :)

2022-02-20 22:05 UTC, rpvsilva submitted a review, later dismissed
LGTM 🔥 Great job!! You are rocking 🚀

2022-02-21 10:40 UTC, merged